---
abstract: 'web page title fetching IRC plugin'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-IRC-Plugin-WWW-GetPageTitle
provides:
  POE::Component::IRC::Plugin::WWW::GetPageTitle:
    file: lib/POE/Component/IRC/Plugin/WWW/GetPageTitle.pm
    version: 1.0103
requires:
  POE::Component::IRC::Plugin::BasePoCoWrap: 0.004
  POE::Component::WWW::GetPageTitle: 0.0101
  URI: 1.35
  URI::Find::Schemeless: 1.8
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 1.0103
