---
name: POE-Component-IRC-Plugin-WWW-GetPageTitle
version: 0.0102
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: web page title fetching IRC plugin
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  POE::Component::IRC::Plugin::BasePoCoWrap: 0.004
  POE::Component::WWW::GetPageTitle: 0.0101
  URI: 1.35
  URI::Find::Schemeless: 1.8
configure_requires:
  Module::Build: 0.34
provides:
  POE::Component::IRC::Plugin::WWW::GetPageTitle:
    file: lib/POE/Component/IRC/Plugin/WWW/GetPageTitle.pm
    version: 0.0102
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
